### ISSUE TITLE
Open redirect in backend locale config template

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-backend#10]
Better not allow `*` as redirect URL in `surf/settings/local.py.template`, in case it gets forgotten to change it creates an open redirect which is a serious issue.

**Comment by ggevorg** [comment]
Template was changed (see https://github.com/surfedushare/surf-backend/blob/master/surf/settings/local.py.template#L20)

**Comment by sveeke** [comment]
Fix is verified and is OK.
