### ISSUE TITLE
Verify SSL is set to false in backend user views

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-backend#11]
In `surf/apps/users/views.py` in line 214 SSL verification is disabled:
>  verify_ssl=_OIDC_CONFIG.get("verify_ssl", False),

**Comment by ggevorg** [comment]
verify_ssl is set from _OIDC_CONFIG and will be set to False only if _OIDC_CONFIG does not contain verify_ssl. I changed False to True (see https://github.com/surfedushare/surf-backend/blob/master/surf/apps/users/views.py#L214), so now verify_ssl is set to True if _OIDC_CONFIG does not contain the parameter.

**Comment by sveeke** [comment]
Fix is verified and is OK
