### ISSUE TITLE
FilterSerializer::update() has no permission checks while create() has

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-backend#12]
It seems creation of filters in the backend `surf/apps/filters/serializer.py` is tightly controlled while updates are not. Maybe updates are checked somewhere else?

**Comment by ggevorg** [comment]
User can update the filter only if he is owner of the filter due to the objects filtration (see https://github.com/surfedushare/surf-backend/blob/master/surf/apps/filters/views.py#L60)

**Comment by sveeke** [comment]
Good enough

**Comment by sveeke** [comment]
I close the issue for now.
