### ISSUE TITLE
Backend cookies can leak due to not setting COOKIES_SECURE

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-backend#8]
To quote the Django security guidelines:

> If a browser connects initially via HTTP, which is the default for most browsers, it is possible for existing cookies to be leaked. For this reason, you should set your SESSION_COOKIE_SECURE and CSRF_COOKIE_SECURE settings to True.

**Comment by ggevorg** [comment]
COOKIE_SECURE parameters are set in backend settings now (see https://github.com/surfedushare/surf-backend/blob/master/surf/settings/base.py#L57).

**Comment by sveeke** [comment]
Fix verified and OK
